
document.addEventListener('DOMContentLoaded', function(event) {
  //the event occurred

  let c = this.getElementById("myCanvas");
  let ctx = c.getContext("2d");

  //This array was generated by d8_v2.js  using the algorithm described in the problem statement
  let arr = [[1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1],
  [1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
  [1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0],
  [1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
  [1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
  [1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0]];
  console.log(arr);

  for (let i = 0; i < 6; i++) {
    for (let j = 0; j < 25; j++) {
      console.log(arr[i][j]);
      if (arr[i][j] === 0) {
        ctx.beginPath();
        ctx.strokeStyle = "black";
        ctx.rect(j * 10, i * 10, 10, 10);
        ctx.fill()
      } else {
        ctx.strokeStyle = "white";
      }

    }
  }
})
